name: Setup
description: Setup
runs:
  using: composite
  steps:
    - uses: volta-cli/action@v4
    # pnpm のキャッシュディレクトリを取得
    - id: pnpm
      shell: bash
      run: echo "cache-dir=$(pnpm store path)" >> $GITHUB_OUTPUT
    # キャッシュをリストア
    - uses: actions/cache@v4
      with:
        path: ${{ steps.pnpm.outputs.cache-dir }}
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-
    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
